### ISSUE TITLE
Incomplete rendering

### ISSUE THREAD

**Issue by kapoun01** [azchohfi/LottieUWP#25] opened 2018-03-12 08:55 UTC
Only part of the animation is rendered. On other platforms or on the web (https://www.lottiefiles.com/preview) it looks good.

[device1.zip](https://github.com/azchohfi/LottieUWP/files/1801999/device1.zip)

**Comment by azchohfi** [comment] 2018-03-12 23:45
Duplicate of #4. We are working on it!

**Closed by azchohfi** 2018-03-12 23:45 UTC
